CREATE TABLE "z_report_runs" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "z_report_runs_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"reportDate" text NOT NULL,
	"runTimestamp" text NOT NULL,
	"runBy" integer
);
--> statement-breakpoint
ALTER TABLE "z_report_runs" ADD CONSTRAINT "z_report_runs_runBy_fkey" FOREIGN KEY ("runBy") REFERENCES "public"."employees"("id") ON DELETE no action ON UPDATE no action;